#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 18:30:34 2020

@author: evanraj
"""

import os
import sys

import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
from matplotlib import cm
plt.rcParams['backend'] = "Qt4Agg"

l_path = '..'
m_path = os.path.abspath(l_path)
if not os.path.exists(m_path):
    print('Error importing modules. Need to specify new path')
    raise Exception
else:
    sys.path.append(m_path)

#import numpy as np
#import scipy as sp
#from scipy.sparse import csr_matrix

from Research import ferro_system1
Ferro_sys = ferro_system1.Ferro_sys

size = 3+2*5
disc = [1, 1, 1]
def sizing(nx):
    size_Ex = np.array([(nx-1)/2, (nx+1)/2, (nx+1)/2])
    size_Ey = np.array([(nx+1)/2, (nx-1)/2, (nx+1)/2])
    size_Ez = np.array([(nx+1)/2, (nx+1)/2, (nx-1)/2])

#    size_Bx = np.array([(nx-3)/2, (nx-1)/2, (nx-1)/2])
#    size_By = np.array([(nx-1)/2, (nx-3)/2, (nx-1)/2])
#    size_Bz = np.array([(nx-1)/2, (nx-1)/2, (nx-3)/2])
    
    size_Bx = np.array([(nx+1)/2, (nx-1)/2, (nx-1)/2])
    size_By = np.array([(nx-1)/2, (nx+1)/2, (nx-1)/2])
    size_Bz = np.array([(nx-1)/2, (nx-1)/2, (nx+1)/2])
    return [size_Ex, size_Ey, size_Ez, size_Bx, size_By, size_Bz]

## To give number of nodes
a = np.array(sizing(size)).prod(axis=1)


E0_x = np.zeros(shape = (int(a[0]),1))
E0_y = np.zeros(shape = (int(a[1]),1))
E0_z = np.zeros(shape = (int(a[2]),1))
B0_x = np.zeros(shape = (int(a[3]),1))
B0_y = np.zeros(shape = (int(a[4]),1))
B0_z = np.zeros(shape = (int(a[5]),1))
M0_x = np.zeros(shape = (int(a[3]),1))
M0_y = np.zeros(shape = (int(a[4]),1))
M0_z = np.zeros(shape = (int(a[5]),1))
E0 = np.array([E0_x, E0_y, E0_z])
H0 = np.array([B0_x, B0_y, B0_z])
M0 = np.array([M0_x, M0_y, M0_z])
H_s = H0

R_sys = Ferro_sys(size,disc,E0,H0,M0,H_s)

def f_x(x,y,z,t):
    if t < 0.2:
        val = 0
    else:
        val = 1
    
    return val

def f_y(x,y,z,t):
    
    val = 0
    
    return val

def f_z(x,y,z,t):
    val = 0
    
    return val

R_sys.fx = f_x
R_sys.fy = f_y
R_sys.fz = f_z

for t in np.arange(0,R_sys.T,R_sys.dt):
    ### re-initializing the system
    R_sys.set_up()
    
    ### Running the system
    R_sys.single_run(t)
    
    ## Updating old fields
    R_sys.E_old = R_sys.E_new.values
    R_sys.H_old = R_sys.H_new.values
    R_sys.M_old = R_sys.M_new.values
    R_sys.B_old = R_sys.B_new.values
    
    print('Current time: ', round(t,1))

## Plotting stuff
# For now, plotting Ex or By

fig = plt.figure()
ax = plt.axes()
E_old = R_sys.E_old

x1 = np.zeros(shape = (E_old.x.nx*E_old.x.ny,1))
y1 = np.zeros(shape = (E_old.x.nx*E_old.x.ny,1))
z1 = np.zeros(shape = (E_old.x.nx*E_old.x.ny,1))

#for k in np.arange(0,E_old.x.nx*E_old.x.ny):
#    x1[k] = R_sys.ind_rev_x_out(k)[0]
#    y1[k] = R_sys.ind_rev_x_out(k)[1]
#    z1[k] = E_old.x.value[k]

for k in np.arange(0,E_old.x.value.shape[0]):
    x1[k] = R_sys.ind_rev_x_out(k)[0]
    y1[k] = R_sys.ind_rev_x_out(k)[1]
    z1[k] = E_old.x.value[k]

x = x1
y = y1
z = z1

#surf = ax.scatter(x, y, s = z/np.linalg.norm(z,axis=1))

plot = ax.pcolormesh(x,y,z)

plt.show()


