#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 18:30:34 2020

@author: evanraj
"""

import os
import sys
from datetime import date

today1 = date.today()
today = today1.strftime("%d_%m_%y")

import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
from matplotlib import cm
plt.rcParams['backend'] = "Qt4Agg"
from collections import OrderedDict
import pandas as pd

l_path = '..'
m_path = os.path.abspath(l_path)
if not os.path.exists(m_path):
    print('Error importing modules. Need to specify new path')
    raise Exception
else:
    sys.path.append(m_path)

#import numpy as np
#import scipy as sp
#from scipy.sparse import csr_matrix

from Research import ferro_system1
Ferro_sys = ferro_system1.Ferro_sys

### Parameters (global)
mu0 = 1.25667e-6
eps = 0.88422e-11
gamma = 2.2e5
K = 0
alpha = 0.2
H_s_val = 10**5

### Parameters (system)
max_x = 16.4
disc = [0.4, 0.4, 0.4]

dt = 5e-10
T = 3*dt

if (max_x/disc[0])%2 == 0:
    print('Warning. Grid could fail, untested')
    size = round(max_x/disc[0])
    
elif (max_x/disc[0])%2 == 1:
    size = round(max_x/disc[0])
    
else:
    print('That domain and disc not available'
          '\n','Attempting closest available disc.')
    max_x = max_x - (max_x/disc[0])%2
    size = round(max_x/disc[0])
    
def sizing(nx,ny,nz):
    if nz != 1:
        size_outer_x = np.array([(nx-1)/2, (ny+1)/2, (nz+1)/2])
        size_outer_y = np.array([(nx+1)/2, (ny-1)/2, (nz+1)/2])
        size_outer_z = np.array([(nx+1)/2, (ny+1)/2, (nz-1)/2])
    
    #    size_Bx = np.array([(nx-3)/2, (nx-1)/2, (nx-1)/2])
    #    size_By = np.array([(nx-1)/2, (nx-3)/2, (nx-1)/2])
    #    size_Bz = np.array([(nx-1)/2, (nx-1)/2, (nx-3)/2])
        
        size_inner_x = np.array([(nx+1)/2, (ny-1)/2, (nz-1)/2])
        size_inner_y = np.array([(nx-1)/2, (ny+1)/2, (nz-1)/2])
        size_inner_z = np.array([(nx-1)/2, (ny-1)/2, (nz+1)/2])
        
    else:
        '''
        Note that for this case, the not-used will have the amount of 
        the field with which they are associated, simply to make concatenation
        work properly
        '''
        size_outer_x = np.array([(nx-1)/2, (ny+1)/2, 1])
        size_outer_y = np.array([(nx+1)/2, (ny-1)/2, 1])
        size_outer_z = np.array([(nx+1)/2, (ny-1)/2, 1]) # This will not be included in calculations
    
    #    size_Bx = np.array([(nx-3)/2, (nx-1)/2, (nx-1)/2])
    #    size_By = np.array([(nx-1)/2, (nx-3)/2, (nx-1)/2])
    #    size_Bz = np.array([(nx-1)/2, (nx-1)/2, (nx-3)/2])
        
        size_inner_x = np.array([(nx-1)/2, (ny-1)/2, 1]) # This will not be included in calculations
        size_inner_y = np.array([(nx-1)/2, (ny-1)/2, 1]) # This will not be included in calculations
        size_inner_z = np.array([(nx-1)/2, (ny-1)/2, 1])
        
    return [size_outer_x, size_outer_y, size_outer_z,\
            size_inner_x, size_inner_y, size_inner_z]

### Initial conditions

# To give number of nodes
a = np.round(np.array(sizing(size,size,1)).prod(axis=1))

####################################################
########### Initial conditions ################
####################################################
E0_x = np.zeros(shape = (int(a[0]),1))
E0_y = np.zeros(shape = (int(a[1]),1))
E0_z = np.zeros(shape = (int(a[2]),1))
E0 = np.concatenate((E0_x, E0_y, E0_z),axis=1).T

B0_x = np.zeros(shape = (int(a[3]),1))
B0_y = np.zeros(shape = (int(a[4]),1))
B0_z = np.zeros(shape = (int(a[5]),1))
B0 = np.concatenate((B0_x, B0_y, B0_z),axis=1).T

M0_x = np.zeros(shape = (int(a[3]),1))
M0_y = np.zeros(shape = (int(a[4]),1))
M0_z = 100*np.ones(shape = (int(a[5]),1)) # Initial conditions for M
M0 = np.concatenate((M0_x, M0_y, M0_z),axis=1).T

H0_x = np.zeros(shape = (int(a[3]),1))
H0_y = np.zeros(shape = (int(a[4]),1))
H0_z = np.zeros(shape = (int(a[5]),1))
H0 = np.concatenate((H0_x, H0_y, H0_z),axis=1).T

H_s_x = H_s_val*np.ones(shape = (int(a[3]),1))
H_s_y = H_s_val*np.ones(shape = (int(a[4]),1))
H_s_z = H_s_val*np.ones(shape = (int(a[5]),1))
H_s = np.concatenate((H_s_x, H_s_y, H_s_z),axis=1).T

R_sys = Ferro_sys(size,disc,E0,H0,M0,H_s)
R_sys.dt = dt

####################################################
#### Boundary conditions, and Forcing terms ########
####################################################

### Some random test code for Forcing conditiosn
#def f_x(x,y,z,t):
#    if t < 0.2:
#        val = 0
#    if x == 0 or x == max_x:
#        val = 0
#    else:
#        val = 0
#    
#    return val
#
#def f_y(x,y,z,t):
#    
#    val = 0
#    if y == 0 or y == max_x:
#        val = 0
#    
#    return val
#
#def f_z(x,y,z,t):
#    val = 0
#    
#    if z == 0 or z == max_x:
#        val = 0
#    
#    return val

#### Ricker Pulse

## Ricker Pulse parameters
beta0 = 4E4
f = 4E7
a = 1.34
b = 3.4
k = (np.pi/a)**2
c = 3E8

def g(x):
    '''
    Actual Ricker pulse function
    '''
    if x < b:
        pa = 2*k/11*(2*k*(x-a)**2-1)
        pb = (np.e**(-k*(x-a)**2))
        
        return pa*pb
    else:
        return 0
    
### Ricker Pulse forcing conditions at x = 0 
### 'Normal' boundary conditions

def f_x(x,y,z,t):
    '''
    Ricker Pulse for x
    '''
    if y < 1E-12: #approx 0
        d = beta0*g(f*t)
        return d
    else:
        return 0
    
def f_y(x,y,z,t):
    '''
    Ricker Pulse for y
    '''
    return 0
    
    
def f_z(x,y,z,t):
    '''
    Ricker Pulse for z
    '''
    return 0

R_sys.fx = f_x
R_sys.fy = f_y
R_sys.fz = f_z

for t in np.arange(dt,T,dt):
    ### re-initializing the system
    R_sys.set_up()
    
    ### Running the system
    R_sys.single_run(t)
    
    ## Updating old fields
    R_sys.E_old2 = R_sys.E_old.values
    R_sys.B_old2 = R_sys.B_old.values
    R_sys.M_old2 = R_sys.M_old.values
    R_sys.H_old2 = R_sys.H_old.values
    
    R_sys.E_old = R_sys.E_new.values
    R_sys.H_old = R_sys.H_new.values
    R_sys.M_old = R_sys.M_new.values
    R_sys.B_old = R_sys.B_new.values
    
    print('Current time: ', '{:.2e}'.format(t))

## Plotting stuff

fig_Mz = R_sys.plot_slice('M','z',10)
fig_Bz = R_sys.plot_slice('B','z',10)
fig_Ez = R_sys.plot_slice('E','z',10)
fig_Hz = R_sys.plot_slice('H','z',10)

def mkdir_p(mypath):
    '''Creates a directory. equivalent to using mkdir -p on the command line'''

    from errno import EEXIST
    from os import makedirs,path

    try:
        makedirs(mypath)
    except OSError as exc: 
        if exc.errno == EEXIST and path.isdir(mypath):
            pass
        else: raise

mkdir_p(today)

## Saving data
name = 'test_new_Fx'

R_sys.save_data(today+'/'+name)

    # Run parameters
        #Global Parameters
data = OrderedDict()
data['mu0'] = mu0
data['eps'] = eps 
data['gamma'] = gamma
data['K'] = K
data['alpha'] = alpha
data['H_s'] = H_s_val

        # Parameters (system)
data['max_x'] = max_x
data['disc'] = disc[0]
data['size'] = size
data['T'] = T
data['dt'] = dt

df = pd.DataFrame([data])
df.to_csv(today+'/'+name+'_param.csv')

fig_Mz.savefig(today+'/'+name+'Mz_10')
fig_Bz.savefig(today+'/'+name+'Bz_10')
fig_Ez.savefig(today+'/'+name+'Ez_10')
fig_Hz.savefig(today+'/'+name+'Hz_10')

def cardanos_method(a,b,c,d,eps = 1E-12):
    '''
    Solves for the real root of a cubic polynomial. 
    Note that it will not solve for the symmetric
    real roots, even if they exist. 
    See here for more explanation:
        https://brilliant.org/wiki/cardano-method/
    '''
    if abs(a) < eps:
        print('*'*40,'\n','Error, not a cubic. Aborting','\n','*'*40)
        raise Exception
        
    def real_cubic_root(arg):
        '''
        Forces python to return the real root of a cubic. 
        Note: "< 0" case works as 
            -(-n)^(1/3) = ((-1)^3(-n))^(1/3) = ((-1)(-n))^(1/3) = (n)^1/3
        '''
        if type(arg) == complex:
            return (arg)**(1/3)
        else:
            if arg < 0:
                return -(-arg)**(1/3)
            else:
                return (arg)**(1/3)
    
    Q = (3*a*c - b**2)/(9*a**2)
    R = (9*a*b*c - 27*a**2*d - 2*b**3)/(54*a**3)
#    
#    if Q**3 > R**2-eps:
#        print('*'*40,'\n','Break. Error in cardanos method, cannot use',
#              'Dont know why, but Q**3 > R**2 is hard.','\n','*'*40)
#        raise Exception
    
    S = real_cubic_root(R + (Q**3 + R**2)**(1/2))
    T = real_cubic_root(R - (Q**3 + R**2)**(1/2))
    print('Q: ',Q,'\n'*2,
          'R: ',R,'\n'*2,
          'S: ',S,'\n'*2,
          'T: ',T,'\n'*2)
    
    root = S+T - (b)/(3*a)
    
    if abs(root.imag) > eps:
        print('Warning. Imaginary part of the root is too large.')
        wait = input('Press ENTER, or CTRL C to break')        
    
    return root.real
    

def det_E_M():
    '''
    Determines the vector of error_moduli for a given system
    as described in running notes 2/13
    '''
    M = R_sys.M_old.values
    
    E_M = abs(np.linalg.norm(M,axis=0) - np.linalg.norm(M0,axis=0))\
    /(np.linalg.norm(M0,axis=0))
    
    return E_M
    



